# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go backend

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'

    - name: go build
      working-directory: ./tonix-backend
      run: go build -v ./...

    - name: go test
      working-directory: ./tonix-backend
      run: go test -v ./...

    - name: go vet
      working-directory: ./tonix-backend
      run: go vet -v ./...
